# Generated by Django 3.0.8 on 2020-10-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
